### ISSUE TITLE
Cannot import name 'ChargeExtractor' running create_pedestal_file.py script

### ISSUE THREAD

**Issue by andres-baquero** [cta-observatory/cta-lstchain#173]
Hello. I'm trying to run the script create_pedestal_file.py on lstchain last version, but I'm getting this error:

**ImportError: cannot import name 'ChargeExtractor' from 'ctapipe.image' (/fefs/aswg/workspace/andres.baquero/miniconda3/envs/cta-lst/lib/python3.7/site-packages/ctapipe/image/__init__.py)**

I guess that ChargeExtractor was replace with WaveformExtractor. 

I recently install the lstchain last version that uses ctapipe master.  So I wonder if  lstchain still pointing to a ctapipe old version ?.

Thanks.

**Comment by vuillaut** [comment]
Hi @andres-baquero 

lstchain should indeed be working with ctapipe v0.7.0 so thank you for reporting this bug.
@FrancaCassol, if you could have a look that would be great, I don't think I'll have time in the coming days.

**Comment by morcuended** [comment]
Hi @vuillaut, @andres-baquero , I just made a fresh installation of lstchain and tested `create_pedestal_file.py` and it runs without errors.

I also noticed during the installation that after the command

`pip install https://github.com/cta-observatory/ctapipe/archive/master.tar.gz`

 I got this:
```
Building wheels for collected packages: ctapipe
  Building wheel for ctapipe (setup.py) ... done
  Created wheel for ctapipe: filename=ctapipe-unknown-cp37-none-any.whl size=295831 sha256=42ee140d73dfda8fbc617b5cacdcebe22b53e21ced7fa2f5df5ac0e9ad4a5b84
  Stored in directory: /tmp/pip-ephem-wheel-cache-0fiiri4w/wheels/74/20/d4/b66f2a634fa6045aba42cc06e5e1a17213f12bc6591a9f5389
Successfully built ctapipe
Installing collected packages: ctapipe
  Found existing installation: ctapipe 0.7.0
    Uninstalling ctapipe-0.7.0:
      Successfully uninstalled ctapipe-0.7.0
Successfully installed ctapipe-unknown
```
Is it installing the proper version of ctapipe? Why is it specified as _ctapipe-unknown_?

**Comment by vuillaut** [comment]
Thanks @morcuended !

>```
>   Found existing installation: ctapipe 0.7.0
>     Uninstalling ctapipe-0.7.0:
>       Successfully uninstalled ctapipe-0.7.0
> Successfully installed ctapipe-unknown
> ```
> 
> Is it installing the proper version of ctapipe? Why is it specified as _ctapipe-unknown_?


So right now, lstchain install is still pointing to ctapipe master branch (will change once PR #163 is merged). In your case it seems you had ctapipe v0.7.0 installed and installing lstchain removed it to install the master branch version (which is > to 0.7.0 but not a released version, so probably why it's tagged as "unknown").

**Comment by andres-baquero** [comment]
Thanks @vuillaut 

Like  @morcuended  says. I made again a fresh installation of lstchain and tested create_pedestal_file.py and it runs without errors. Aparently something wronged in my previous installation.

Sorry for the inconvenience.
